-- Corrected migration, generated by Sieve.
-- The original change was rated HIGH (35/100).
-- It has been rewritten into the safe, phased rollout below. Each phase is
-- self-contained and must ship on its own — do not bundle them into one PR.

-- ============================================================
-- Phase 1: Additive — ships immediately
-- When: Ship in this PR.
-- Add the new shape alongside the old. No reads or writes use it yet.
-- ============================================================
BEGIN;
-- Sieve could not auto-generate phase 1 SQL for this specific diff.
-- Recommended pattern: ADD column/table without removing existing structure.
COMMIT;

-- ============================================================
-- Phase 2: Cleanup — after soak
-- When: Ship in a SEPARATE PR, after a soak period (>= 7 days).
-- Drop the deprecated structure once the new shape has been the source of truth for ≥ 7 days.
-- ============================================================
BEGIN;
-- Drop the deprecated structure here.
COMMIT;
