-- Corrected migration, generated by Sieve.
-- The original change was rated CRITICAL (90/100).
-- It has been rewritten into the safe, phased rollout below. Each phase is
-- self-contained and must ship on its own — do not bundle them into one PR.

-- ============================================================
-- Phase 1: Stop writing to the column
-- When: Deploy together with the application release that needs it.
-- Application release that removes all reads and writes of Envelope.CONSTRAINT. No schema change yet.
-- ============================================================
-- No SQL in this phase — application code change only.
-- After this release ships, Envelope.CONSTRAINT is unused and safe to drop.

-- ============================================================
-- Phase 2: Drop column — separate PR after 7-day soak
-- When: Ship in a SEPARATE PR, after a soak period (>= 7 days).
-- DESTRUCTIVE. Irreversible without backup restore.
-- ============================================================
BEGIN;

ALTER TABLE "Envelope" DROP COLUMN "CONSTRAINT";

COMMIT;
